# Generated by Django 6.0 on 2026-01-04 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalRaro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("nome_cientifico", models.CharField(max_length=200)),
                ("texto", models.TextField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("MAMIFERO", "Mamífero"),
                            ("AVE", "Ave"),
                            ("REPTIL", "Réptil"),
                            ("ANFIBIO", "Anfíbio"),
                            ("PEIXE", "Peixe"),
                            ("INSETO", "Inseto"),
                        ],
                        default="MAMIFERO",
                        max_length=10,
                    ),
                ),
                (
                    "estado_conservacao",
                    models.CharField(
                        choices=[
                            ("CR", "Criticamente em Perigo"),
                            ("EM", "Em Perigo"),
                            ("VU", "Vulnerável"),
                            ("NT", "Quase Ameaçada"),
                            ("LC", "Pouco Preocupante"),
                        ],
                        default="VU",
                        max_length=2,
                    ),
                ),
                ("regiao_brasil", models.CharField(max_length=100)),
                ("imagem_url", models.URLField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("publicado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
